# Automated Windows (MSVC++) testing using appveyor.com
# https://ci.appveyor.com/projects

version: 1.0.{build}

branches:
  except:
    - gh-pages

os: Visual Studio 2017

environment:
  # update the vcpkg cache even if build fails
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  matrix:
      - platform: x86
      - platform: x64

cache:
  - c:\Tools\vcpkg\installed

clone_script:
  - cmd: >-
      git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive

build_script:
  - if "%platform%" == "x86" vcpkg install roaring:x86-windows
  - if "%platform%" == "x64" vcpkg install roaring:x64-windows
  - cd %APPVEYOR_BUILD_FOLDER%
  - if "%platform%" == "x86" cmake -G "Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  - if "%platform%" == "x64" cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  - cmake -CMAKE_C_FLAGS="/arch:AVX2" -CMAKE_C_FLAGS="/arch:AVX2" --build . --config Release

test_script:
  - ps: C:\projects\FastIntersectCount\Release\benchmark.exe